### ISSUE TITLE
去掉空间右侧的「大家都在看」和「礼物」两个区块

### ISSUE THREAD

**Issue by meowtec** [candywxt/qzonemore#1]
以及左侧的「猜你感兴趣」「大家都在玩」「发现生活」

首先应该学会使用 Chrome 开发者工具中的 `Elements` 项。
通过查看 dom 结构，想办法使用 js 选择器准确选择节点，将其移除。

需要熟练掌握：
- 开发者工具的使用
- 选择器的使用
- DOM 操作

@candywxt

**Comment by candywxt** [comment]
写出来啦~orz,原来这么简单~

**Comment by candywxt** [comment]
等等，我发现我没有把右边的移除掉，我看了看那两个div:大家都在看和礼物这两个节点，是独立的节点，我今天看了那个教程说寻找节点有以下几种方法：
1、childNodes 返回一个数组，这个数组由给定元素节点的子节点构成；
2、firstChild  返回第一个子节点；
3、lastChild  返回最后一个子节点；
4、parentNode 返回一个给定节点的父节点；
5、nextSibling 返回给定节点的下一个子节点；
6、priviousSibling 返回给定节点的上一个子节点；
右边的”大家都在看“和”礼物“这两个节点应该找到和他同级的节点，通过方法5来get,我明天把代码贴上来。
今天把慕课的教程JS内容看完了。
明天看jQuery~~
